# Generated by Django 4.2 on 2023-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_cita', models.DateTimeField()),
                ('cp', models.PositiveBigIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('nhc', models.CharField(max_length=10)),
                ('movil', models.PositiveBigIntegerField()),
                ('agenda', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
