# Generated by Django 4.1.7 on 2023-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_datos', '0002_alter_datos_agenda_alter_datos_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='DNI',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='dato',
            name='incidencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
