# Generated by Django 4.2 on 2023-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_datos', '0004_remove_dato_incidencia_dato_incidencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
