# Generated by Django 4.2 on 2023-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=9)),
                ('nhc', models.CharField(max_length=10)),
                ('movil', models.PositiveBigIntegerField()),
                ('cp', models.PositiveBigIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('dia_cita', models.DateField()),
                ('agenda', models.CharField(choices=[('HF_FARDISP', 'HF_FARDISP'), ('HF_UPCCFAR', 'HF_UPCCFAR'), ('HF_FAR4', 'HF_FAR4')], default='none', max_length=30)),
                ('incidencia', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Sin revisar', 'Sin revisar'), ('Entregado', 'Entregado'), ('No entregado: Dirección erronea', 'No entregado: Dirección erronea'), ('No entregado: No hay nadie en casa', 'No entregado: No hay nadie en casa')], default='none', max_length=100)),
            ],
        ),
    ]
