# Generated by Django 4.2 on 2023-04-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(blank=True, max_length=9, null=True)),
                ('nhc', models.CharField(max_length=10)),
                ('movil', models.PositiveBigIntegerField()),
                ('cp', models.PositiveBigIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('dia_cita', models.DateTimeField()),
                ('agenda', models.CharField(choices=[('HF_FARDISP', 'HF_FARDISP'), ('HF_UPCCFAR', 'HF_UPCCFAR'), ('HF_FAR4', 'HF_FAR4')], default='none', max_length=30)),
                ('incidencia', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Sin revisar', 'Sin revisar'), ('Entregado', 'Entregado'), ('No entregado: Dirección erronea', 'No entregado: Dirección erronea'), ('No entregado: No hay nadie en casa', 'No entregado: No hay nadie en casa')], default='none', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
