# Generated by Django 4.2 on 2023-04-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_pedido_delete_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='incidencia',
            new_name='incidencias',
        ),
    ]
